"""Prometheus text exposition for counters the platform already keeps.

Nothing here instruments anything new. `WorkerStats`, `BridgeStats`,
`NormalizerStats`, `ProcessorStats` and `ConsumerStats` are already maintained
by the ingestion layer, and the executor registry already tracks containments
-- they were simply unreadable outside a `/ingestion/status` JSON blob that no
scraper understands.

FORMAT
------
Plain text, generated by hand rather than via `prometheus_client`. The library
would be a 1 MB dependency to render forty lines of `name{label="x"} 1.0`, and
it insists on a process-global registry that fights the platform's own
singletons.

NAMING
------
`cs_<subsystem>_<thing>_<unit>`, per Prometheus convention: counters end in
`_total`, gauges do not. The names are stable API -- a dashboard breaks if
they change.
"""
from __future__ import annotations

from typing import Any, Iterable


def _escape(value: str) -> str:
    """Escape a label value per the exposition format."""
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
    )


class MetricsWriter:
    """Accumulates metric families in Prometheus text exposition format."""

    def __init__(self) -> None:
        self._lines: list[str] = []
        self._declared: set[str] = set()

    def add(
        self,
        name: str,
        value: Any,
        *,
        kind: str = "gauge",
        help_text: str = "",
        labels: dict[str, Any] | None = None,
    ) -> None:
        """Append one sample, declaring its family on first use.

        Non-numeric and non-finite values are skipped rather than emitted as
        `NaN`: a scraper reading NaN as a real measurement is worse than a
        missing series.
        """
        try:
            numeric = float(value)
        except (TypeError, ValueError):
            return
        if numeric != numeric or numeric in (float("inf"), float("-inf")):
            return

        if name not in self._declared:
            if help_text:
                self._lines.append(f"# HELP {name} {help_text}")
            self._lines.append(f"# TYPE {name} {kind}")
            self._declared.add(name)

        if labels:
            rendered = ",".join(
                f'{k}="{_escape(v)}"' for k, v in sorted(labels.items())
            )
            self._lines.append(f"{name}{{{rendered}}} {numeric}")
        else:
            self._lines.append(f"{name} {numeric}")

    def add_many(
        self,
        prefix: str,
        stats: dict[str, Any],
        *,
        counters: Iterable[str] = (),
        help_text: str = "",
    ) -> None:
        """Emit every numeric field of a stats dict under one prefix."""
        counter_fields = set(counters)
        for field, value in stats.items():
            if field.startswith("_"):
                continue
            name = f"{prefix}_{field}"
            is_counter = field in counter_fields or field.endswith(
                ("_total", "processed", "published", "consumed", "acked",
                 "dropped", "rejected", "failed", "skipped", "extracted",
                 "built", "run")
            )
            self.add(
                name,
                value,
                kind="counter" if is_counter else "gauge",
                help_text=help_text,
            )

    def render(self) -> str:
        # The exposition format requires a trailing newline.
        return "\n".join(self._lines) + "\n"


def render_platform_metrics(platform: Any, event_log: Any = None) -> str:
    """Render the whole platform's current counters.

    Every value is read defensively: /metrics must not be the endpoint that
    takes the server down, and a half-initialised platform is a normal state
    during startup and after an artifact failure.
    """
    w = MetricsWriter()

    # ── Readiness ────────────────────────────────────────────────────────────
    w.add(
        "cs_platform_ready",
        1 if getattr(platform, "ready", False) else 0,
        help_text="1 when model artifacts and the agent runtime are loaded.",
    )
    w.add(
        "cs_memory_available",
        1 if getattr(platform, "memory_provider", None) is not None else 0,
        help_text="1 when the memory provider is usable (alerts, audit, learning).",
    )

    artifacts = getattr(platform, "artifacts", None)
    if artifacts is not None:
        w.add(
            "cs_anomaly_layer_active",
            1 if getattr(artifacts, "anomaly_ready", False) else 0,
            help_text="1 when the unsupervised anomaly layer runs alongside the classifier.",
        )
        feature_cols = getattr(artifacts, "feature_cols", None)
        if feature_cols is not None:
            w.add(
                "cs_model_feature_count",
                len(feature_cols),
                help_text="Number of features the served model expects.",
            )

    # ── Ingestion ────────────────────────────────────────────────────────────
    service = getattr(platform, "ingestion_service", None)
    if service is not None:
        try:
            running = service.is_running()
        except Exception:
            running = False
        w.add(
            "cs_ingestion_running",
            1 if running else 0,
            help_text="1 while the capture worker thread is alive.",
        )

        stats = getattr(service, "stats", None)
        if stats is not None and hasattr(stats, "as_dict"):
            w.add_many(
                "cs_ingestion_worker",
                stats.as_dict(),
                counters=("polls", "files_processed", "flows_published",
                          "events_processed", "sweeps", "errors"),
                help_text="Ingestion worker loop counters.",
            )

        bridge = getattr(service, "bridge", None)
        if bridge is not None and hasattr(bridge, "stats"):
            w.add_many(
                "cs_bridge",
                bridge.stats.as_dict(),
                help_text="Flows consumed and run through the agent pipeline.",
            )

        processor = getattr(service, "processor", None)
        if processor is not None and hasattr(processor, "stats"):
            w.add_many(
                "cs_pcap",
                processor.stats.as_dict(),
                help_text="Capture files converted into flows.",
            )
            normalizer = getattr(processor, "normalizer", None)
            if normalizer is not None and hasattr(normalizer, "stats"):
                n = normalizer.stats
                w.add("cs_normalizer_flows_normalized_total",
                      n.flows_normalized, kind="counter",
                      help_text="Flows converted to the model's feature contract.")
                w.add("cs_normalizer_rejected_total", n.rejected, kind="counter",
                      help_text="Flows refused for violating the feature contract.")
                w.add("cs_normalizer_non_finite_clamped_total",
                      n.non_finite_clamped, kind="counter",
                      help_text="Feature values clamped from inf/NaN.")
                w.add("cs_normalizer_missing_values_filled_total",
                      n.missing_values_filled, kind="counter",
                      help_text="Missing features zero-filled (non-strict mode only).")

        producer = getattr(service, "producer", None)
        if producer is not None and hasattr(producer, "stats"):
            w.add_many("cs_stream_producer", producer.stats.as_dict(),
                       help_text="Redis Stream publish counters.")

        consumer = getattr(service, "consumer", None)
        if consumer is not None and hasattr(consumer, "stats"):
            w.add_many("cs_stream_consumer", consumer.stats.as_dict(),
                       help_text="Redis Stream consume counters.")

    # ── Response ─────────────────────────────────────────────────────────────
    agent = getattr(platform, "response_agent", None)
    registry = getattr(agent, "executor_registry", None)
    if registry is not None:
        executors = getattr(registry, "_registered", [])
        w.add(
            "cs_response_executors_registered",
            len(executors),
            help_text="Integrations available to execute a decided action.",
        )
        for executor in executors:
            # SimulatedContainmentExecutor exposes its ledger; notification and
            # future real integrations do not hold state and simply skip.
            active_entries = getattr(executor, "active_entries", None)
            if callable(active_entries):
                try:
                    w.add(
                        "cs_response_active_containments",
                        len(active_entries()),
                        labels={"executor": getattr(executor, "executor_name", "unknown")},
                        help_text="Containments currently in force.",
                    )
                except Exception:
                    pass

    # ── Activity feed ────────────────────────────────────────────────────────
    if event_log is not None:
        w.add(
            "cs_events_emitted_total",
            event_log.latest_seq(),
            kind="counter",
            help_text="Platform log events captured for the live feed.",
        )

    return w.render()
