"""Synthetic and replayed traffic driven through the real agent pipeline.
"""
from __future__ import annotations

import random

import pandas as pd
from fastapi import APIRouter, File, HTTPException, UploadFile
from fastapi.responses import JSONResponse

from api.projections import iso_utc
from api.runtime import ensure_runtime, platform
from cyber_surakshya.platform.actions.action_type import ActionType
from cyber_surakshya.platform.audit.metadata import AuditMetadata
from cyber_surakshya.platform.enums.event_source import EventSource
from cyber_surakshya.platform.enums.event_type import EventType
from cyber_surakshya.platform.enums.severity import Severity
from cyber_surakshya.platform.identifiers.correlation import CorrelationContext
from cyber_surakshya.platform.risk.score import RiskScore
from cyber_surakshya.platform.schemas.response_result import ResponseStatus
from cyber_surakshya.platform.schemas.security_event import NetworkEndpoint, SecurityEvent
from cyber_surakshya.platform.state import create_initial_state

router = APIRouter(tags=["simulation"])


# Simulation profiles are loaded once by api.runtime.load_attack_profiles()
# and live on `platform.attack_profiles`. Each is a complete 42-feature
# median vector over real labelled CICIDS2017 flows, so nothing is
# zero-filled on the way to the model.
#
# Regenerate after retraining:  python scripts/build_attack_profiles.py
@router.post("/simulation/simulate-attack")
def simulate_attack():
    runtime = ensure_runtime()
    if runtime is None:
        raise HTTPException(status_code=503, detail="LangGraph runtime not initialized")

    if not platform.attack_profiles:
        raise HTTPException(
            status_code=503,
            detail=(
                "No simulation profiles available. Generate them from the "
                "training data with: python scripts/build_attack_profiles.py"
            ),
        )

    # 1. Select a random flow profile. Each is a complete 42-feature median
    #    vector taken from real labelled CICIDS2017 flows, so nothing is
    #    zero-filled on the way to the model.
    attack_name, features = random.choice(list(platform.attack_profiles.items()))
    features_copy = {name: float(value) for name, value in features.items()}
    src_ip = f"{random.randint(10, 192)}.{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}"

    # 2. Build SecurityEvent with real numeric flow features
    ctx = CorrelationContext.create()
    event = SecurityEvent(
        correlation_id=ctx.correlation_id,
        trace_id=ctx.trace_id,
        event_type=EventType.NETWORK_FLOW,
        source=EventSource.IDS,
        severity=Severity.INFO,
        risk_score=RiskScore(value=0.0),
        title=f"Network flow simulation: {attack_name}",
        network=NetworkEndpoint(
            source_ip=src_ip,
            destination_ip="192.168.1.100",
            destination_port=int(features_copy.get("Destination Port", 80))
        ),
        raw_payload=features_copy,
        features={k: float(v) for k, v in features_copy.items() if isinstance(v, (int, float))},
        audit=AuditMetadata(
            created_by="simulator",
            updated_by="simulator",
            source_system="simulation_endpoint"
        )
    )
    
    # 3. Create initial state and run real ML Pipeline via LangGraph
    state = create_initial_state(context=ctx)
    state.security_events.append(event)
    
    output_state = runtime.execute(state)
    
    # 4. Extract real ML detection & analysis results
    if not output_state.detection_results:
        raise HTTPException(status_code=500, detail="No detection result generated by ML pipeline")
    
    det = output_state.detection_results[0]
    analysis = output_state.analysis_results[0] if output_state.analysis_results else None
    
    # The alert id IS the detection id. It used to be a fresh uuid4 appended to
    # MOCK_ALERTS, which meant the id returned here existed nowhere else: the
    # DetectionAgent had already persisted the same detection under its own id,
    # so /alerts showed a different record and this one 404'd on click.
    alert_id = str(det.detection_id)
    is_attack = det.predicted_label.upper() != "BENIGN"

    # Projected in the same shape /alerts returns, from the same values that
    # were just persisted. No separate mock store.
    new_alert = {
        "id": alert_id,
        "attack_type": det.predicted_label,
        "source_ip": src_ip,
        "severity": det.severity.name.upper(),
        "status": "Investigating" if is_attack else "Resolved",
        "created_at": iso_utc(det.detected_at),
    }

    new_analysis = None
    if analysis:
        new_analysis = {
            "id": str(analysis.analysis_id),
            "alert_id": alert_id,
            "prediction": det.predicted_label,
            "confidence": round(det.confidence * 100, 2),
            "summary": analysis.summary
        }

    # Containment is no longer fabricated here. The ResponseAgent node in the
    # pipeline authorised and executed (or refused) the decided action; we
    # simply report what it did.
    response = output_state.response_results[0] if output_state.response_results else None
    decision = output_state.decision_results[0] if output_state.decision_results else None

    blocked_obj = None
    if response is not None and response.status == ResponseStatus.EXECUTED and \
            response.action.action_type in (ActionType.BLOCK_IP, ActionType.ISOLATE_HOST,
                                            ActionType.RATE_LIMIT):
        blocked_obj = {
            "id": response.response_id,
            "ip": response.action.target.target_value,
            "reason": f"Detected {det.predicted_label} (Confidence: {round(det.confidence * 100, 1)}%)",
            "action": response.action.action_type.value,
            "created_at": response.executed_at.isoformat(),
        }

    return JSONResponse(content={
        "alert": new_alert,
        # The AnalysisAgent's own output when it ran, including its summary
        # and the analysis_id the dashboard needs to link to /analyses. The
        # previous shape restated the detection and dropped both.
        "analysis": new_analysis or {
            "prediction": det.predicted_label,
            "confidence": round(det.confidence * 100, 2),
            "summary": None,
        },
        "threat_score": {
            "score": det.risk_score.value,
            "risk": det.risk_score.level.name if det.risk_score.level else "MODERATE",
            "priority": det.severity.name
        },
        "decision": {
            "action": decision.action.action_type.value if decision else None,
            "priority": decision.priority.value if decision else None,
            "requires_approval": decision.requires_approval if decision else None,
            "rationale": decision.rationale if decision else None,
        },
        "response": {
            "action": response.action.action_type.value if response else "NONE",
            "status": response.status.value if response else "NO_RESPONSE",
            "guard_verdict": response.guard_verdict.value if response else None,
            "guard_rule": response.guard_rule if response else None,
            "guard_reason": response.guard_reason if response else None,
            "trust_tier": response.engine_trust_tier.value if response else None,
            "executor": response.executor_name if response else None,
        },
        "blocked_ip": blocked_obj
    })

@router.post("/simulation/upload-zeek")
async def upload_zeek_simulation(file: UploadFile = File(...)):
    runtime = ensure_runtime()
    if runtime is None:
        raise HTTPException(status_code=503, detail="LangGraph production runtime not initialized")
    
    try:
        contents = (await file.read()).decode("utf-8")
        import tempfile
        from io import StringIO

        from inference import translate_zeek_conn_log
        
        with tempfile.NamedTemporaryFile(mode="w+", delete=False, suffix=".log") as tmp:
            tmp.write(contents)
            tmp.flush()
            
            with open(tmp.name) as f:
                lines = [
                    line for line in f
                    if not line.startswith("#separator")
                    and not line.startswith("#set_separator")
                ]
            header_line = None
            data_lines = []
            for line in lines:
                if line.startswith("#fields"):
                    header_line = line.strip().replace("#fields\t", "").split("\t")
                elif not line.startswith("#"):
                    data_lines.append(line)
                    
            if header_line is None:
                df_zeek = pd.read_csv(tmp.name, sep="\t", comment="#")
            else:
                data_str = "".join(data_lines)
                df_zeek = pd.read_csv(StringIO(data_str), sep="\t", names=header_line, na_values=["-", "(empty)"])
                
        # Translate directly to features without predicting!
        df_translated = translate_zeek_conn_log(df_zeek)
            
        alerts_generated = []
        analyses_generated = []
        blocked_ips = []
        attacks_found = 0
        
        # Limit to 50 rows to avoid extremely long synchronous loops
        for _idx, row in df_translated.head(50).iterrows():
            src_ip = f"{random.randint(10, 192)}.{random.randint(1, 255)}.{random.randint(1, 255)}.{random.randint(1, 255)}"
            
            # Use strict type checking, fill NaN with 0.0
            features = {k: float(v) if pd.notnull(v) else 0.0 for k, v in row.to_dict().items()}
            
            ctx = CorrelationContext.create()
            event = SecurityEvent(
                correlation_id=ctx.correlation_id,
                trace_id=ctx.trace_id,
                event_type=EventType.NETWORK_FLOW,
                source=EventSource.IDS,
                severity=Severity.INFO,
                risk_score=RiskScore(value=0.0),
                title="Zeek Upload - Direct ML Process",
                network=NetworkEndpoint(
                    source_ip=src_ip,
                    destination_ip="192.168.1.100",
                    destination_port=int(row.get("Destination Port", 0))
                ),
                features=features,
                audit=AuditMetadata(
                    created_by="zeek_upload",
                    updated_by="zeek_upload",
                    source_system="simulation_endpoint"
                )
            )
            
            state = create_initial_state(context=ctx)
            state.security_events.append(event)
            # Run through PRODUCTION adapter directly (real ML model)
            output_state = runtime.execute(state)
            
            if output_state.detection_results:
                det = output_state.detection_results[0]
                if det.status.value != "benign":
                    attacks_found += 1
                    analysis = output_state.analysis_results[0] if output_state.analysis_results else None
                    
                    # Same identity rule as /simulation/simulate-attack: the
                    # alert id is the detection id that was just persisted, so
                    # the id returned here resolves in /alerts.
                    alert_id = str(det.detection_id)
                    new_alert = {
                        "id": alert_id,
                        "attack_type": det.predicted_label,
                        "source_ip": src_ip,
                        "severity": det.severity.name.upper(),
                        "status": "Investigating",
                        "created_at": iso_utc(det.detected_at),
                    }
                    alerts_generated.append(new_alert)

                    if analysis:
                        new_analysis = {
                            "id": str(analysis.analysis_id),
                            "alert_id": alert_id,
                            "prediction": det.predicted_label,
                            "confidence": round(det.confidence * 100, 2),
                            "summary": analysis.summary
                        }
                        analyses_generated.append(new_analysis)
                        
                    # Report the containment the ResponseAgent actually
                    # performed, rather than assuming every attack was blocked.
                    resp = (
                        output_state.response_results[0]
                        if output_state.response_results
                        else None
                    )
                    if resp is not None and resp.status == ResponseStatus.EXECUTED:
                        blocked_ips.append({
                            "id": resp.response_id,
                            "ip": resp.action.target.target_value,
                            "reason": f"Detected {det.predicted_label}",
                            "action": resp.action.action_type.value,
                            "created_at": resp.executed_at.isoformat(),
                        })
                
        return JSONResponse(content={
            "processed_records": len(df_translated.head(50)),
            "attacks_found": attacks_found,
            "alerts": alerts_generated,
            "analyses": analyses_generated,
            "blocked_ips": blocked_ips
        })
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Zeek upload simulation failed: {e}")
